// Vercel Serverless Function — proxies OpenAI writing evaluation server-side
// This avoids browser-level CORS / firewall blocks on api.openai.com

export default async function handler(req, res) {
  // Only allow POST
  if (req.method !== "POST") {
    return res.status(405).json({ _error: "Method not allowed" });
  }

  const OPENAI_KEY = process.env.VITE_OPENAI_API_KEY || "";
  if (!OPENAI_KEY) {
    return res.status(500).json({ _error: "OpenAI API key not configured on server. Add VITE_OPENAI_API_KEY to Vercel environment variables." });
  }

  const { text, taskMeta } = req.body || {};
  if (!text) {
    return res.status(400).json({ _error: "No writing text provided." });
  }

  const wordCount = text.trim().split(/\s+/).filter(Boolean).length;

  const systemPrompt = `You are Nova, LingvoConnect's AI IELTS Writing Examiner. You evaluate writing professionally, clearly, and supportively — never harsh, never robotic. Communicate in a slightly formal, IELTS-like tone.

Score the writing on all 4 official IELTS criteria AND detect if the response appears AI-generated. Return ONLY valid JSON — no markdown, no extra text — in this exact shape:
{"band":6.5,"taskAchievement":{"band":6.5,"comment":"Your argument addresses the task clearly, though some points would benefit from further development."},"coherenceCohesion":{"band":7.0,"comment":"Your ideas are logically organised, but linking devices could be more varied throughout."},"lexicalResource":{"band":6.5,"comment":"Good use of topic-specific vocabulary, though some repetition reduces the overall impact."},"grammaticalRange":{"band":6.0,"comment":"You demonstrate a reasonable range of structures, but some grammatical errors reduce clarity."},"wordCount":160,"summary":"A well-structured response that addresses the task. Developing your arguments further and varying your vocabulary will help raise your band score.","strengths":["Your ideas are clear and relevant to the topic.","Good use of topic-specific vocabulary in key sections."],"improvements":["Try to extend your main ideas with clearer, more specific examples.","Some grammatical errors reduce the overall clarity of your response."],"suggestions":["Use more complex sentence structures to demonstrate grammatical range.","Support your arguments with specific, real-world examples.","Avoid repeating simple vocabulary — vary your word choices."],"keyTip":"Focus on clarity over complexity — this is key to reaching Band 7+.","corrections":[{"original":"phrase from text","corrected":"corrected version","note":"brief reason"}],"aiDetection":{"risk":25,"verdict":"Human","signals":["natural hesitations present","minor grammatical errors typical of humans"],"explanation":"The response displays characteristics consistent with human writing."}}

=== AI DETECTION RULES (apply these STRICTLY) ===
You must independently assess whether this text was written by a human or generated by an AI (ChatGPT, Claude, Gemini, etc.). Be STRICT and err on the side of flagging AI content — it is better to flag a human as "Possibly AI" than to miss actual AI-generated text.

STRONG AI SIGNALS (each adds 15-25 to risk score):
- Perfect or near-perfect grammar with zero natural errors or slips
- Formal academic transition phrases used mechanically: "Furthermore,", "Moreover,", "In addition,", "In conclusion,", "It is worth noting that", "This is particularly evident in", "Undoubtedly,", "Notably,"
- Every paragraph has identical structure: topic sentence → 2 support points → mini-conclusion
- Sentences are uniformly long and complex with no variation in rhythm
- No personal voice, no colloquialisms, no casual phrasing anywhere
- Uses vague, hedged language throughout: "some may argue", "it could be said", "in many respects"
- No specific personal examples — only generic examples like "students", "society", "the environment"
- The response perfectly addresses every part of the prompt without any omission or misunderstanding
- Vocabulary is consistently advanced and formal with no register shifts
- No run-on sentences, no fragments, no self-corrections, no repetitions typical of human writing
- Overly balanced arguments that present "both sides" without taking a clear personal stance

HUMAN SIGNALS (each reduces risk score by 10-20):
- Minor grammatical errors, spelling slips, or awkward phrasing
- Personal anecdotes or specific real-life references
- Sentence length variation including short punchy sentences
- Informal phrases or colloquial expressions mixed in
- Clear personal opinions stated directly ("I strongly believe", "I think this is wrong")
- Some repetition of vocabulary or ideas
- Slight off-topic moments or imprecise answers
- Natural connectors: "Also,", "But,", "So,", "That said,"
- Contractions used occasionally

SCORING GUIDE:
- 0-25 (Human): Clear natural writing with multiple human signals and few/no AI signals
- 26-55 (Possibly AI): Some AI signals present but mixed with human characteristics; uncertain
- 56-80 (Likely AI): Multiple strong AI signals; very clean, structured, formal throughout
- 81-100 (AI Generated): Almost all AI signals present; reads like a model answer or ChatGPT output; near-perfect grammar, formulaic structure, no personal voice

IMPORTANT: If you see 3+ strong AI signals, the risk score MUST be at least 56. If you see 5+ strong AI signals with no human signals, the risk score MUST be 80+. Do NOT be lenient. Real IELTS candidates at all band levels make errors and show personal voice.

Verdict must be "Human" (0-25%), "Possibly AI" (26-55%), "Likely AI" (56-80%), or "AI Generated" (81-100%). Risk is integer 0-100. Use 0.5 band increments 1–9. Be strict, realistic, and consistent with official IELTS standards.`;

  const userPrompt = `IELTS Writing ${taskMeta?.task || "Task"}\n\nPrompt: ${taskMeta?.prompt || "IELTS Writing Task"}\n\nCandidate's response (${wordCount} words):\n${text}`;

  try {
    const openaiRes = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${OPENAI_KEY}`,
      },
      body: JSON.stringify({
        model: "gpt-4o",
        max_tokens: 1600,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user",   content: userPrompt },
        ],
      }),
    });

    const data = await openaiRes.json();

    if (!openaiRes.ok || data.error) {
      return res.status(502).json({ _error: `OpenAI error: ${data.error?.message || `HTTP ${openaiRes.status}`}` });
    }

    const raw = (data.choices?.[0]?.message?.content || "").replace(/```json|```/g, "").trim();
    if (!raw) {
      return res.status(502).json({ _error: "Empty response from OpenAI." });
    }

    const parsed = JSON.parse(raw);
    return res.status(200).json(parsed);

  } catch (e) {
    return res.status(500).json({ _error: `Server error: ${e.message || "Could not reach OpenAI."}` });
  }
}
